# Generated by Django 6.0.6 on 2026-07-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='semester',
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartHubApp.student'),
        ),
    ]
