# Generated by Django 6.0.6 on 2026-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
