# Generated by Django 6.0.6 on 2026-06-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHubApp', '0003_announcement_election_lecturer_unit_venue_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHubApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=200)),
                ('unit_code', models.CharField(max_length=20)),
                ('teaching_rating', models.CharField(max_length=20)),
                ('communication_rating', models.CharField(max_length=20)),
                ('punctuality_rating', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartHubApp.student')),
            ],
        ),
    ]
